const images = {
  background: require('../../assets/images/BG.png'),
  logoImage: require('../../assets/images/logoSettings.png'),
  buttonProceedWhite: require('../../assets/images/buttonProceedWhite.png'),
  backgroundImage: require('../../assets/images/backgroundImage.png'),
  iconCalendarsmall: require('../../assets/images/iconCalendarsmall.png'),
  // iconClocksmall: require('../../assets/images/iconClocksmall.png'),
  aboutCompanyPanel500px: require('../../assets/images/aboutCompanyPanel500px.png'),
  drawerBackground: require('../../assets/images/drawerBackground.png'),
  // twit: require('../../assets/images/twit.png'),
  // g: require('../../assets/images/g.png'),
  // share: require('../../assets/images/share.png'),
  contractDefault: require('../../assets/images/contractDefault.png'),
  contractSelected: require('../../assets/images/contractSelected.png'),
  calculatorDefault: require('../../assets/images/calculatorDefault.png'),
  calculatorSelected: require('../../assets/images/calculatorSelected.png'),
  taxDefault: require('../../assets/images/taxDefault.png'),
  taxSelected: require('../../assets/images/taxSelected.png'),
  newspaperDefault: require('../../assets/images/newspaperDefault.png'),
  newspaperSelected: require('../../assets/images/newspaperSelected.png'),
  // iconServices: require('../../assets/images/iconServices.png'),
  servicesImagex: require('../../assets/images/servicesImagex.png'),
  taxesImage: require('../../assets/images/taxesImage.png'),
  drawerLogo: require('../../assets/images/drawerLogo.png'),
  incentiveImage: require('../../assets/images/incentiveImage.png'),
  splash: require('../../assets/images/splash.png'),
  hlbServicesPhoto: require('../../assets/images/hlbServicesPhoto.jpg')
};

export default images;
